name: angel
description: An easily-extensible web server framework in Dart.
publish_to: none # Ensure we don't accidentally publish our private code! ;)
environment:
  sdk: ">=1.19.0"
homepage: https://github.com/angel-dart/angel
dependencies:
  angel_framework: ^1.1.0-alpha # The core server library.
  angel_serialize: ^1.0.0-alpha # Model definition metadata.

  angel_auth: ^1.1.0-alpha # Supports stateless authentication via JWT
  angel_configuration: ^1.1.0-alpha # Loads application configuration, along with support for .env files.
  angel_cors: ^1.0.0 # CORS support
  angel_jael: ^1.0.0-alpha # Server-side templating engine
  angel_static: ^1.3.0-alpha # Static file server
  angel_validate: ^1.0.0 # Allows for validation of input data
dev_dependencies:
  angel_hot: ^1.1.0-alpha # Hot-reloading support. :)
  angel_serialize_generator: ^1.0.0-alpha # Generates serialization code for models.
  angel_test: ^1.1.0-alpha # Utilities for testing Angel servers.
  build_runner: ^0.5.0
  grinder: ^0.8.0
  test: ^0.12.13
transformers:
  # Injects data from application configuration into Dart code.
  #
  # Documentation:
  # https://github.com/angel-dart/configuration
  - angel_configuration
