name: angel
description: An easily-extensible web server framework in Dart.
publish_to: none # Ensure we don't accidentally publish our private code! ;)
environment:
  sdk: '>=2.0.0-dev <2.0.0'
homepage: https://github.com/angel-dart/angel
dependencies:
  angel_auth: ^1.1.0 # Supports stateless authentication via JWT
  angel_configuration: ^1.1.0 # Loads application configuration, along with support for .env files.
  angel_cors: ^1.0.0 # CORS support
  angel_framework: ^1.1.0 # The core server library.
  angel_jael: ^1.0.0 # Server-side templating engine
  angel_serialize: ^2.0.0 # Model definition metadata.
  angel_static: ^1.3.0 # Static file server
  angel_validate: ^1.0.0 # Allows for validation of input data
dev_dependencies:
  angel_hot: ^1.1.0-alpha # Hot-reloading support. :)
  angel_serialize_generator: ^2.0.0 # Generates serialization code for models.
  angel_test: ^1.1.0 # Utilities for testing Angel servers.
  build_runner: ^0.7.0
  console: ^2.2.4
  grinder: ^0.8.0
  test: ^0.12.13