name: angel
description: An easily-extensible web server framework in Dart.
publish_to: none
environment:
  sdk: ">=1.19.0"
homepage: https://github.com/angel-dart/angel
dependencies: 
  angel_common: ^1.0.0
  angel_configuration: ^1.0.0
  angel_multiserver: ^1.0.0
dev_dependencies:
  grinder: ^0.8.0
  http: ^0.11.3
  test: ^0.12.13
transformers: 
  - angel_configuration
